# Generated by Django 5.0.6 on 2024-07-01 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=50)),
                ('arte', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.genero')),
            ],
        ),
    ]
