# Generated by Django 5.0.6 on 2024-07-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genero',
            new_name='Tipo',
        ),
    ]
